apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-connect-demo-config
  namespace: demo
data:
  CONNECT_REST_PORT: "8083"
  CONNECT_GROUP_ID: "kafka-connect-demo-cluster"
  CONNECT_CONFIG_STORAGE_TOPIC: "kafka-connect-demo-config"
  CONNECT_OFFSET_STORAGE_TOPIC: "kafka-connect-demo-offsets"
  CONNECT_STATUS_STORAGE_TOPIC: "kafka-connect-demo-status"
  connect-avro-status: "3"
  CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "3"
  CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "3"
  CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "3"
  CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
  CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
  CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
  CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
  CONNECT_LOG4J_ROOT_LOGLEVEL: "INFO"
  CONNECT_PLUGIN_PATH: "/etc/kafka-connect/jars"
  SCHEMA_REGISTRY_HOST_NAME_CONFIG: "kafka-connect-demo.demo"
  SCHEMA_REGISTRY_URL_CONFIG: "http://kafka-connect-demo.demo.svc.cluster.local:8081"